// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TETHER.Data;

#nullable disable

namespace TETHER.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TETHER.Models.Entities.PriorityLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PriorityLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Low"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            Name = "High"
                        });
                });

            modelBuilder.Entity("TETHER.Models.Entities.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Name = "In Progress"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Completed"
                        });
                });

            modelBuilder.Entity("TETHER.Models.Entities.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocsLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PmId")
                        .HasColumnType("int");

                    b.Property<int>("PriorityLevelId")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectManagerId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PriorityLevelId");

                    b.HasIndex("ProjectManagerId");

                    b.HasIndex("StatusId");

                    b.ToTable("TaskItems");
                });

            modelBuilder.Entity("TETHER.Models.Entities.TaskItemAssignment", b =>
                {
                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("AssignedTo")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TeamMemberId")
                        .HasColumnType("int");

                    b.HasKey("TaskId", "AssignedTo");

                    b.HasIndex("TeamMemberId");

                    b.ToTable("TaskItemAssignments");
                });

            modelBuilder.Entity("TETHER.Models.Entities.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GithubUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalGmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PmId")
                        .HasColumnType("int");

                    b.Property<string>("ProfileImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectManagerId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SchoolGmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectManagerId");

                    b.HasIndex("RoleId");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Reina Chloe",
                            GithubUsername = "reicdm",
                            LastName = "Magpantay",
                            MiddleName = "De Roja",
                            Password = "pm012345",
                            PersonalGmail = "rcdrmagpantay@gmail.com",
                            ProfileImageUrl = "/images/member-image/rei.jpg",
                            RoleId = 1,
                            SchoolGmail = "reinachloedmagpantay@iskolarngbayan.pup.edu.ph"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Johanna Angela",
                            GithubUsername = "johannaestalilla1205",
                            LastName = "Estalilla",
                            MiddleName = "Quilatan",
                            Password = "member01",
                            PersonalGmail = "pupbsitestalillajohanna@gmail.com",
                            PmId = 1,
                            ProfileImageUrl = "/images/member-image/hanna.jpg",
                            RoleId = 2,
                            SchoolGmail = "johannaangelapestalilla@iskolarngbayan.pup.edu.ph"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Sarah Mae",
                            GithubUsername = "smhix",
                            LastName = "Harina",
                            MiddleName = "Dela Cruz",
                            Password = "member02",
                            PersonalGmail = "sarahmaeharina@gmail.com",
                            PmId = 1,
                            ProfileImageUrl = "/images/member-image/sarah.jpg",
                            RoleId = 3,
                            SchoolGmail = "sarahmaedharina@iskolarngbayan.pup.edu.ph"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Josiah Zachary",
                            GithubUsername = "znacku",
                            LastName = "Sy",
                            MiddleName = "Quinones",
                            Password = "member03",
                            PersonalGmail = "bsitsyjosiah@gmail.com",
                            PmId = 1,
                            ProfileImageUrl = "/images/member-image/zach.jpg",
                            RoleId = 3,
                            SchoolGmail = "josiahzacharyqsy@iskolarngbayan.pup.edu.ph"
                        });
                });

            modelBuilder.Entity("TETHER.Models.Entities.TeamMemberRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeamMemberRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Project Manager"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Backend Developer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Frontend Developer"
                        });
                });

            modelBuilder.Entity("TETHER.Models.Entities.TaskItem", b =>
                {
                    b.HasOne("TETHER.Models.Entities.PriorityLevel", "PriorityLevel")
                        .WithMany("Tasks")
                        .HasForeignKey("PriorityLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TETHER.Models.Entities.TeamMember", "ProjectManager")
                        .WithMany()
                        .HasForeignKey("ProjectManagerId");

                    b.HasOne("TETHER.Models.Entities.Status", "Status")
                        .WithMany("Tasks")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriorityLevel");

                    b.Navigation("ProjectManager");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TETHER.Models.Entities.TaskItemAssignment", b =>
                {
                    b.HasOne("TETHER.Models.Entities.TaskItem", "Task")
                        .WithMany("Assignments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TETHER.Models.Entities.TeamMember", "TeamMember")
                        .WithMany()
                        .HasForeignKey("TeamMemberId");

                    b.Navigation("Task");

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("TETHER.Models.Entities.TeamMember", b =>
                {
                    b.HasOne("TETHER.Models.Entities.TeamMember", "ProjectManager")
                        .WithMany()
                        .HasForeignKey("ProjectManagerId");

                    b.HasOne("TETHER.Models.Entities.TeamMemberRole", "Role")
                        .WithMany("TeamMembers")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectManager");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TETHER.Models.Entities.PriorityLevel", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TETHER.Models.Entities.Status", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TETHER.Models.Entities.TaskItem", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("TETHER.Models.Entities.TeamMemberRole", b =>
                {
                    b.Navigation("TeamMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
